[package]
name = "sleep"
version = "0.0.1"
authors = []

[lib]
name = "uu_sleep"
path = "sleep.rs"

[dependencies]
getopts = "0.2.14"
uucore = { path="../uucore" }

[[bin]]
name = "sleep"
path = "main.rs"
