[package]
name = "date"
version = "0.0.1"
authors = []

[lib]
name = "uu_date"
path = "date.rs"

[dependencies]
chrono = "0.4.0"
clap = "2.24.1"
uucore = { path="../uucore" }

[[bin]]
name = "date"
path = "main.rs"
