[package]
name = "rmdir"
version = "0.0.1"
authors = []

[lib]
name = "uu_rmdir"
path = "rmdir.rs"

[dependencies]
getopts = "0.2.14"
uucore = { path="../uucore" }

[[bin]]
name = "rmdir"
path = "main.rs"
