[package]
name = "mkfifo"
version = "0.0.1"
authors = []

[lib]
name = "uu_mkfifo"
path = "mkfifo.rs"

[dependencies]
getopts = "0.2.14"
libc = "0.2.26"
uucore = { path="../uucore" }

[[bin]]
name = "mkfifo"
path = "main.rs"
