[package]
name = "pathchk"
version = "0.0.1"
authors = []

[lib]
name = "uu_pathchk"
path = "pathchk.rs"

[dependencies]
getopts = "0.2.14"
libc = "0.2.26"
uucore = { path="../uucore" }

[[bin]]
name = "pathchk"
path = "main.rs"
