[package]
name = "hostname"
version = "0.0.1"
authors = []

[lib]
name = "uu_hostname"
path = "hostname.rs"

[dependencies]
libc = "0.2.26"
uucore = { path="../uucore" }

[[bin]]
name = "hostname"
path = "main.rs"
