---
- name: Create monitoring addons directory
  file: path=/etc/kubernetes/addons/monitoring state=directory mode=0755

- name: Install monitoring addons
  template: src="monitoring/{{ item }}.yaml.j2" dest="/etc/kubernetes/addons/monitoring/{{ item }}.yaml" mode=0644
  with_items:
    - node-exporter-ds
    - prometheus-rc
    - prometheus-svc
    - grafana-rc
    - grafana-svc
