[package]
name = "pinky"
version = "0.0.1"
authors = []

[lib]
name = "uu_pinky"
path = "pinky.rs"

[dependencies.uucore]
path = "../uucore"
default-features = false
features = ["utmpx", "entries"]

[[bin]]
name = "pinky"
path = "main.rs"
