[package]
name = "relpath"
version = "0.0.1"
authors = []

[lib]
name = "uu_relpath"
path = "relpath.rs"

[dependencies]
getopts = "0.2.14"
uucore = { path="../uucore" }

[[bin]]
name = "relpath"
path = "main.rs"
