[package]
name = "mknod"
version = "0.0.1"
authors = []

[lib]
name = "uu_mknod"
path = "mknod.rs"

[dependencies]
getopts = "0.2.14"
libc = "^0.2.4"
uucore = { path="../uucore" }

[[bin]]
name = "mknod"
path = "main.rs"
