[package]
name = "tty"
version = "0.0.1"
authors = []

[lib]
name = "uu_tty"
path = "tty.rs"

[dependencies]
getopts = "0.2.14"
libc = "0.2.26"
uucore = { path="../uucore" }

[[bin]]
name = "tty"
path = "main.rs"
