[package]
name = "unexpand"
version = "0.0.1"
authors = []

[lib]
name = "uu_unexpand"
path = "unexpand.rs"

[dependencies]
getopts = "0.2.14"
unicode-width = "0.1.4"
uucore = { path="../uucore" }

[[bin]]
name = "unexpand"
path = "main.rs"
