---
- name: Install kubelet kubeconfig
  template:
    src=kubelet.kubeconfig.j2
    dest=/etc/kubernetes/kubelet.kubeconfig
    mode=0644
  register: kube_config1

- name: Install kube config
  template:
    src=kube-config.j2
    dest=/etc/kubernetes/config
    mode=0644

- name: Install kubernetes configuration files
  template:
    src="{{ item }}.j2"
    dest="/etc/kubernetes/{{ item }}"
    mode=0644
  with_items:
    - kubelet
    - apiserver
    - proxy
    - scheduler
    - controller-manager
  register: kube_config2

- include: upstart-config.yml
  when: init_system == "upstart"

- include: systemd-config.yml
  when: init_system == "systemd"

- name: Setting kube_modified fact to true
  set_fact:
    kube_modified: true
  when: kube_config1.changed == true or kube_config2.changed == true or kube_config3.changed == true
