---
- name: Install kubernetes systemd service files
  template:
    src="{{ item }}.service.j2"
    dest="/etc/systemd/system/{{ item }}.service"
    mode=0644
  with_items:
    - kubelet
    - kube-apiserver
    - kube-proxy
    - kube-scheduler
    - kube-controller-manager
  register: kube_config3

- name: Reload systemd
  command: systemctl --system daemon-reload
  when: kube_config3.changed == true
