---
- name: Set facts for alias
  set_fact:
    gcr: gcr.io/google_containers
    script_dir: "{{ playbook_dir }}/scripts"

- name: Get basic images
  shell: "./get-image.sh {{ image_dir }}/{{ item.tar }}.tar {{ item.img }}"
  args:
    chdir: "{{ script_dir }}"
  register: output
  changed_when: "'already exist' not in output.stdout"
  with_items:
    - { tar: 'pause-amd64_{{ pause_version }}', img: '{{ gcr }}/pause-amd64:{{ pause_version }}' }
    - { tar: 'kube-addon-manager-amd64_v{{ kube_addon_manager_version }}', img: '{{ gcr }}/kube-addon-manager-amd64:v{{ kube_addon_manager_version }}' }
    - { tar: 'exechealthz-amd64_{{ exechealthz_version }}', img: '{{ gcr }}/exechealthz-amd64:{{ exechealthz_version }}' }
    - { tar: 'kubedns-amd64_{{ kubedns_version }}', img: '{{ gcr }}/kubedns-amd64:{{ kubedns_version }}' }
    - { tar: 'kube-dnsmasq-amd64_{{ kube_dnsmasq_version }}', img: '{{ gcr }}/kube-dnsmasq-amd64:{{ kube_dnsmasq_version }}'}
    - { tar: 'dnsmasq-metrics-amd64_{{ dnsmasq_metrics_version }}', img: '{{ gcr }}/dnsmasq-metrics-amd64:{{ dnsmasq_metrics_version }}' }
    - { tar: 'calico-cni_v{{ calico_cni_version }}', img: 'calico/cni:v{{ calico_cni_version }}' }
    - { tar: 'calico-ctl_v{{ calico_ctl_version }}', img: 'calico/ctl:v{{ calico_ctl_version }}' }
    - { tar: 'calico-node_v{{ calico_node_version }}', img: 'quay.io/calico/node:v{{ calico_node_version }}' }

- name: Get kube-policy-controller image
  shell: "./get-image.sh {{ image_dir }}/kube-policy-controller_v{{ kube_policy_controller_version }}.tar calico/kube-policy-controller:v{{ kube_policy_controller_version }}"
  args:
    chdir: "{{ script_dir }}"
  register: output
  changed_when: "'already exist' not in output.stdout"
  when: kube_network_policy

- name: Get dashboard image
  shell: "./get-image.sh {{ image_dir }}/kubernetes-dashboard-amd64_v{{ kubernetes_dashboard_version }}.tar {{ gcr }}/kubernetes-dashboard-amd64:v{{ kubernetes_dashboard_version }}"
  args:
    chdir: "{{ script_dir }}"
  register: output
  changed_when: "'already exist' not in output.stdout"
  when: kube_ui

- name: Get cluster logging images
  shell: "./get-image.sh {{ image_dir }}/{{ item.tar }}.tar {{ item.img }}"
  args:
    chdir: "{{ script_dir }}"
  register: output
  changed_when: "'already exist' not in output.stdout"
  with_items:
    - { tar: 'elasticsearch_v{{ elasticsearch_version }}', img: '{{ gcr }}/elasticsearch:v{{ elasticsearch_version }}' }
    - { tar: 'kibana_v{{ kibana_version  }}', img: '{{ gcr }}/kibana:v{{ kibana_version }}' }
    - { tar: 'fluentd-elasticsearch_{{ fluentd_elasticsearch_version }}', img: '{{ gcr }}/fluentd-elasticsearch:{{ fluentd_elasticsearch_version }}' }
  when: cluster_logging

- name: Get cluster monitoring images
  shell: "./get-image.sh {{ image_dir }}/{{ item.tar }}.tar {{ item.img }}"
  args:
    chdir: "{{ script_dir }}"
  register: output
  changed_when: "'already exist' not in output.stdout"
  with_items:
    - { tar: 'node-exporter_v{{ node_exporter_version }}', img: 'prom/node-exporter:v{{ node_exporter_version }}' }
    - { tar: 'prometheus_v{{ prometheus_version }}', img: 'prom/prometheus:v{{ prometheus_version }}' }
    - { tar: 'grafana_{{ grafana_version }}', img: 'grafana/grafana:{{ grafana_version }}' }
  when: cluster_monitoring
