---
- hosts: localhost
  connection: local
  tasks:
  - name: CentOS 7 or RHEL 7 is supported
    assert: 
      that:
        - "ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'"
        - "ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'"
        - "ansible_distribution_major_version == '7'"
