---
- hosts: localhost
  connection: local
  vars:
    os_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
    os_username: "{{ lookup('env','OS_USERNAME') }}"
    os_password: "{{ lookup('env','OS_PASSWORD') }}"
    os_project_name: "{{ lookup('env','OS_TENANT_NAME') }}"
    os_region_name: "{{ lookup('env','OS_REGION_NAME') }}"
    instances:
      webserver:
        hostname: web.example.com
        security_groups: webserver
        flavor: m3.medium
      appserver:
        hostname: app.example.com
        security_groups: appserver
        flavor: m3.medium
      dbserver:
        hostname: db.example.com
        security_groups: dbserver
        flavor: m3.xlarge
  tasks:
    - name: create instances
      os_server:
        name: "{{ item.key }}"
        state: present
        timeout: 600
        image: 8335a68a-4cde-4337-965a-316d9cd58e42
        key_name: default
        security_groups: "{{ item.value.security_groups }}"
        flavor: "{{ item.value.flavor }}"
        nics:
          - net-id:   5a0f8eec-85ca-4f1a-bc42-51946c9ac65b
        meta:
          hostname: "{{ item.value.hostname }}"
      with_dict: "{{ instances }}"
