---
- hosts: localhost
  connection: local
  vars:
    os_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
    os_username: "{{ lookup('env','OS_USERNAME') }}"
    os_password: "{{ lookup('env','OS_PASSWORD') }}"
    os_project_name: "{{ lookup('env','OS_TENANT_NAME') }}"
    os_region_name: "{{ lookup('env','OS_REGION_NAME') }}"
  tasks:
    - name: remove instances
      os_server:
        name: {{ item }}
        state: absent
        timeout: 600
      with_items:
        - appserver
        - dbserver
