[package]
name = "truncate"
version = "0.0.1"
authors = []

[lib]
name = "uu_truncate"
path = "truncate.rs"

[dependencies]
getopts = "0.2.14"
uucore = { path="../uucore" }

[[bin]]
name = "truncate"
path = "main.rs"
