[package]
name = "tail"
version = "0.0.1"
authors = []

[lib]
name = "uu_tail"
path = "tail.rs"

[dependencies]
getopts = "0.2.14"
kernel32-sys = "0.2.2"
libc = "0.2.26"
winapi = "0.2.8"
uucore = { path="../uucore" }

[[bin]]
name = "tail"
path = "main.rs"
