- name: ***********
  address: **.**.**.**
  port: **
  log_setting:
    - log_dir: /var/log/
      include: ["*.gz"]
    - log_dir: /var/adm/
      include: ["*.gz"]
    - log_dir: /var/cron/
      include: ["*.gz"]
