[package]
name = "split"
version = "0.0.1"
authors = []

[lib]
name = "uu_split"
path = "split.rs"

[dependencies]
getopts = "0.2.14"
uucore = { path="../uucore" }

[[bin]]
name = "split"
path = "main.rs"
