---
- name: Add dockerproject key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add dockerproject repo for debian
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo debian-jessie main'
    state=present
  when: ansible_distribution == 'Debian'

- name: Add dockerproject repo for ubuntu
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state=present
  when: ansible_distribution == 'Ubuntu'

- name: Install docker
  apt:
    name="docker-engine=1.12.*"
    state=present
    force=yes
    install_recommends=no
    update_cache=yes
