[package]
name = "stdbuf"
version = "0.0.1"
authors = []

[lib]
name = "uu_stdbuf"
path = "stdbuf.rs"

[dependencies]
getopts = "0.2.14"
uucore = { path="../uucore" }

[[bin]]
name = "stdbuf"
path = "main.rs"
