[package]
name = "nohup"
version = "0.0.1"
authors = []

[lib]
name = "uu_nohup"
path = "nohup.rs"

[dependencies]
getopts = "0.2.14"
libc = "0.2.26"
uucore = { path="../uucore" }

[[bin]]
name = "nohup"
path = "main.rs"
