# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170713_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='school_year',
            field=models.IntegerField(default=0, verbose_name='school_year'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
        ),
    ]
