[package]
name = "od"
version = "0.0.1"
authors = []

[lib]
name = "uu_od"
path = "od.rs"

[dependencies]
getopts = "0.2.14"
libc = "0.2.26"
byteorder = "1.1.0"
half = "1.0.0"
uucore = { path="../uucore" }

[[bin]]
name = "od"
path = "main.rs"
