[package]
name = "whoami"
version = "0.0.1"
authors = []

[lib]
name = "uu_whoami"
path = "whoami.rs"

[dependencies]
getopts = "0.2.14"
winapi = "0.2.8"
advapi32-sys = "0.2.0"

[dependencies.uucore]
path = "../uucore"
default-features = false
features = ["entries"]

[[bin]]
name = "whoami"
path = "main.rs"
