virt-install \
  --name centos7 \
  --hvm \
  --virt-type kvm \
  --ram 1024 \
  --vcpus 1 \
  --arch x86_64 \
  --os-type linux \
  --os-variant rhel7 \
  --boot hd \
  --disk /data/kvm_disks/centos.img,format=qcow2,size=10 \
  --network bridge=br0 \
  --graphics none \
  --serial pty \
  --console pty \
  --location /data/CentOS-7-x86_64-Minimal-1611.iso \
  --initrd-inject /root/centos7.ks.cfg \
  --extra-args "inst.ks=file:/centos7.ks.cfg console=ttyS0"
