[package]
name = "expand"
version = "0.0.1"
authors = []

[lib]
name = "uu_expand"
path = "expand.rs"

[dependencies]
unicode-width = "0.1.4"
getopts = "0.2.14"
uucore = { path="../uucore" }

[[bin]]
name = "expand"
path = "main.rs"
