[package]
name = "who"
version = "0.0.1"
authors = []

[lib]
name = "uu_who"
path = "who.rs"

[dependencies.uucore]
path = "../uucore"
default-features = false
features = ["utmpx"]

[dependencies.clippy]
version = "0.0.143"
optional = true

[[bin]]
name = "who"
path = "main.rs"
