---
- name: Enable kubernetes services
  service: name={{ item }} enabled=yes
  with_items:
    - kubelet
    - kube-proxy

- name: Start kubelet service
  service: name={{ item }} state=started
  with_items:
    - kubelet
    - kube-proxy
  register: kube_started
