---
- name: Install upstart conf files
  template:
    src="{{ item }}.upstart.j2"
    dest="/etc/init/{{ item }}.conf"
    mode=0644
  with_items:
    - kubelet
    - kube-proxy
  register: kube_config3
