[package]
name = "printf"
version = "0.0.1"
authors = ["Nathan Ross"]

[lib]
name = "uu_printf"
path = "printf.rs"

[dependencies]
"itertools" = "0.6.0"
uucore = { path="../uucore" }

[[bin]]
name = "printf"
path = "main.rs"
