---
- hosts: tag_role_web
  become: true
  serial: 1
  pre_tasks:
    - name: Gathering ec2 facts
      ec2_facts:
      tags:
        - always
      register:  ec2_find

    - debug: var=ec2_find

    - name: Instance De-register
      local_action: ec2_elb
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        state: absent
        wait_timeout: 300
      tags:
        - always

    - debug: var=ec2_elbs

  roles:
    - { role: nginx, tags: [nginx] }
  post_tasks:
    - name: Instance Register
      local_action: ec2_elb
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{{ item }}"
        state: present
        wait_timeout: 300
      with_items: "{{ ec2_elbs }}"
      tags:
        - always
