---
- name: Configure etcd
  template: src=etcd.j2 dest=/etc/etcd/etcd mode=0644
  register: etcd_config1

- include: systemd-config.yml
  when: init_system == "systemd"

- include: upstart-config.yml
  when: init_system == "upstart"

- name: Setting etcd_modified fact to true
  set_fact:
    etcd_modified: true
  when: etcd_config1.changed == true or etcd_config2.changed == true
