---
- name: Install systemd files
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service mode=0644
  register: etcd_config2

- name: Reload systemd
  command: systemctl --system daemon-reload
  when: etcd_config2.changed == true
