[package]
name = "mkdir"
version = "0.0.1"
authors = []

[lib]
name = "uu_mkdir"
path = "mkdir.rs"

[dependencies]
getopts = "0.2.14"
libc = "0.2.26"
uucore = { path="../uucore" }

[[bin]]
name = "mkdir"
path = "main.rs"
