[package]
name = "readlink"
version = "0.0.1"
authors = []

[lib]
name = "uu_readlink"
path = "readlink.rs"

[dependencies]
getopts = "0.2.14"
libc = "0.2.26"
uucore = { path="../uucore" }

[[bin]]
name = "readlink"
path = "main.rs"
