[package]
name = "shuf"
version = "0.0.1"
authors = []

[lib]
name = "uu_shuf"
path = "shuf.rs"

[dependencies]
getopts = "0.2.14"
rand = "0.3.15"
uucore = { path="../uucore" }

[[bin]]
name = "shuf"
path = "main.rs"
