[package]
name = "factor"
version = "0.0.1"
authors = []

[lib]
name = "uu_factor"
path = "factor.rs"

[dependencies]
rand = "0.3.15"
uucore = { path="../uucore" }

[[bin]]
name = "factor"
path = "main.rs"
