[package]
name = "more"
version = "0.0.1"
authors = []

[lib]
name = "uu_more"
path = "more.rs"

[dependencies]
getopts = "0.2.14"
uucore = { path="../uucore" }

[target.'cfg(all(unix, not(target_os = "fuchsia")))'.dependencies]
nix = "0.8.1"

[[bin]]
name = "more"
path = "main.rs"
